### ISSUE TITLE
When searching motifs with () brackets the API is not able to find the entity

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#114]
I am not certain why this is but it is an issue when working on the motif overview page.

Here is my API query:

curl -g -H content-type:application/json http://localhost:8000/rest/widget/motif/\(AAAAATGT\)n/overview | jq '.' 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    53  100    53    0     0   3445      0 --:--:-- --:--:-- --:--:--  3533
{
  "message": "Entity motif (AAAAATGT)n does not exist"

http://www.wormbase.org/resources/motif/(AAAAATGT)n#0--10

I am not sure if the issue is the clojure code or if the solution lies in the pseudoace.

**Comment by mgrbyte** [comment]
As per my comments over on slack (#schema-questions):
During the conversion process, entities that would have no data (other than a primary identifier/name) are discarded.
In the case of Motif, there are 24401 such cases, where the only populated tag(s)  in ACeDDB reside under the `Homol` tag (which has been deliberately excluded)

**Comment by mgrbyte** [comment]
Braces in the the lookup fro motifs were not a factor, but an issue with the conversion process.
Tracking [this issue][1] over in pseudoace - pls open a separate issue for tracking any widgets that need such data if required.

[1]: /WormBase/pseudoace/issues/75
