### ISSUE TITLE
Which interactions to show in the Cytoscape.js figure

### ISSUE THREAD

**Issue by sibyl229** [WormBase/wormbase_rest#119]
Hi @mgrbyte , I talked with @chris-grove at the Worm meeting about which interactions should be showing in the Cytoscape.js figure. Can I double-check with you that's what interaction_details field is returning? In particular, for the nearby edges, @chris-grove seems to mean the edges between genes that are direct interactors of the query genes. Thoughts? Thanks!

**Comment by mgrbyte** [comment]
Discussed off-line on slack (Answer was that Sibyl's interpretation was correct)
Context: Issue with the speed of the interaction_details widget
[Resolved by fixing datalog issue](#117)
Please re-open if more questions.
