### ISSUE TITLE
Failing test "test-alleles-and-polymorphisms"

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#124]
This test is failing when being used with the database WS260.

**Comment by sibyl229** [comment]
@a8wright the test is passing for me somehow with WS260 database. I tried deleting the target/ folder, tests still pass. Could you try deleting your target/ folder?

**Comment by adamjohnwright** [comment]
I am not getting this issue any more. it could have easily been caused by something in the target folder.
