### ISSUE TITLE
Is Street Address ordered in WS260 ?

### ISSUE THREAD

**Issue by azurebrd** [WormBase/wormbase_rest#129]
I thought it was supposed to be, but maybe it's still in progress.

I'm querying :

[:find (pull ?address [*])
 :where
 [?person :person/id "WBPerson363"]
 [?person :person/address ?address]
]

And getting

{:address/street-address ["1200 E California Blvd" "California
Institute of Technology" "Division of Biology and Biological
Engineering 156-29" "Pasadena, CA 91125"], :address/country "United
States of America", :address/institution ["California Institute of
Technology; Pasadena CA, United States of America"],
:address/main-phone ["(626) 395-2687"], :address/web-page
["http://elegans.swmed.edu/CeRD/showhit.cgi?hit=417"], :address/fax
["(626) 395-8611"], :db/id 10572903902068943, :importer/temp
"[:person/id \"WBPerson363\"] :person/address", :address/email
["raymond@caltech.edu"]}

which doesn't have any order information within street-address, nor a 
separate field that would map the order.

By contrast, paper's authors are ordered with an :ordered/index field

[:find (pull ?author [*])
 :where
 [?paper :paper/id "WBPaper00000003"]
 [?paper :paper/author ?author]
]

{:db/id 10959931996912411, :importer/temp "[:paper/id \"WBPaper00000003\"] :paper/author Abdul Kader N", :ordered/index 0, :paper.author/author {:db/id 10911553483240332}, :affiliation/person [{:db/id 10572903901809127}]}
{:db/id 10959931996912410, :importer/temp "[:paper/id \"WBPaper00000003\"] :paper/author Brun J", :ordered/index 1, :paper.author/author {:db/id 10911553483245906}, :affiliation/person [{:db/id 10572903901839378}]}

This first came up here : 
https://github.com/WormBase/datomic-to-catalyst/issues/93

**Comment by mgrbyte** [comment]
@azurebrd Not in WS260, will be in WS261, see [here][1].

[1]: /WormBase/pseudoace/issues/68

**Comment by azurebrd** [comment]
That's great, thanks @mgrbyte !
