### ISSUE TITLE
Data missing in Datomic and in the Transgene widget on the Phenotype page

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#140]
The Over-expressed gene field on the "Transgenes NOT associated with this phenotype" table in the transgene widget on the Phenotype page there is a significant amount of missing data. 

Example widget: wormbase.org/species/all/phenotype/WBPhenotype:0000520#05--10

This Chris Grove said he looked in the AceDB database and could see the data under phenotype-infor/caused-by field. It is not clear why the information is missing both in production and Datomic. This datomic widget will be released with WS261 release as it is missing data in production as well.

**Comment by mgrbyte** [comment]
@a8wright I (think) I see the data in datomic. From a REPL session using the WS261 db in ddb:
```
rest-api.main> (def pt (d/entity db [:phenotype/id "WBPhenotype:0000520"]))

#'rest-api.main/pt
rest-api.main> (some->> (:transgene.phenotype-not-observed/_phenotype pt)
                        (map :phenotype-info/caused-by-gene)
                        (map first)
                        (map :phenotype-info.caused-by-gene/gene)
                        (map :gene/public-name))
("unc-18" "cdc-7" "uaf-1" "uaf-1")
```

**Comment by adamjohnwright** [comment]
@mgrbyte Thanks you for looking into this one. The issue is that I was using the field caused-by not caused-by-gene. Not sure how I got this mixed up. But it is not producing the genes.

I am very happy to know that we are fixing an issue from production!
