### ISSUE TITLE
Data missing from datomic for the variation widget on the phenotype page WS261

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#141]
In the "Variations NOT associated with this phenotype" table on the variation widget on the Phenotype page there is a missing data issue. 

This table can be seen here: http://www.wormbase.org/species/all/phenotype/WBPhenotype:0000520#6--10

When pulling this data from Datomic all information is populated correctly other than the Gene field. For aexample with the variation am120 there is a gene listed from AceDB but not when pulled from Datomic. 

At this point I believe it is a data issue although I am not sure what could be causing this.

**Comment by mgrbyte** [comment]
@a8wright After staring hard at this for a few hours, we think:

 * The data is correct (there is no association between variation `am120` and gene `haly-1` in datomic __or__ ACeDB for WS261.

You can see this using Tree display on the website:
http://www.wormbase.org/tools/tree/run?name=WBVar00000127;class=Variation
(There is no Gene connection to that variation)

Not sure _why_ this is being shown by the current widget?;
looking at the current Perl catalyst code, is possible that this data is stale (e.g being  [cached][1] somehow)?

@Paul-Davis has also been cross-checking:
he found that the counts are slightly off between staging and production (158 vs 159 for Not_in_variation for this phenotype) - the actual data can be seen under tree display. 
He has also checked back 2 or 3 releases and cannot find any association between variation am120 & gene haly-1.

[1]: https://github.com/WormBase/website/blob/staging/lib/WormBase/API/Object/Phenotype.pm#L509

**Comment by adamjohnwright** [comment]
@mgrbyte Thanks for looking into this. I am very confused as well on how it is producing this data. As far as I am aware, there is no caching on staging. I really would like to know why it is showing this but I have also already put a fair bit of effort figuring it out and it is not clear, in the Perl code, where it is coming from. 

I have uncommented the widget on the develop branch, as we believe what it is producing is correct.

Thanks for looking into this!
