### ISSUE TITLE
Interaction widget timing out

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#143]
e.g. http://www.wormbase.org/species/c_elegans/gene/WBGene00002299#8--10

This is the log from EB: 

2017/11/06 03:37:01 [warn] 13623#0: duplicate MIME type "text/html" in /etc/nginx/sites-enabled/elasticbeanstalk-nginx-docker-proxy.conf:11
2017/11/06 10:48:22 [error] 26069#0: *51188 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 52.23.219.146, server: , request: "GET /rest/widget/gene/WBGene00000908/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00000908/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 10:48:52 [error] 26069#0: *51205 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 34.228.239.232, server: , request: "GET /rest/widget/gene/WBGene00000908/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00000908/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 10:57:33 [error] 26069#0: *51450 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 34.228.239.232, server: , request: "GET /rest/widget/gene/WBGene00001184/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00001184/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 11:21:07 [error] 26068#0: *52048 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 34.228.239.232, server: , request: "GET /rest/widget/gene/WBGene00004774/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00004774/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 11:21:37 [error] 26068#0: *52069 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 52.23.219.146, server: , request: "GET /rest/widget/gene/WBGene00004774/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00004774/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 11:22:01 [error] 26068#0: *52073 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 34.228.239.232, server: , request: "GET /rest/widget/gene/WBGene00001184/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00001184/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 11:22:08 [error] 26068#0: *52081 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 52.23.219.146, server: , request: "GET /rest/widget/gene/WBGene00002299/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00002299/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 11:22:30 [error] 26068#0: *52098 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 52.23.219.146, server: , request: "GET /rest/widget/gene/WBGene00001184/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00001184/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"
2017/11/06 11:22:38 [error] 26068#0: *52100 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 34.228.239.232, server: , request: "GET /rest/widget/gene/WBGene00002299/interactions HTTP/1.1", upstream: "http://172.17.0.3:3000/rest/widget/gene/WBGene00002299/interactions", host: "datomic-to-catalyst-ws261.us-east-1.elasticbeanstalk.com"

**Comment by mgrbyte** [comment]
@a8wright @sibyl229 My working assumption is that the interaction widget was being pre-cached.
This timeout seems to suggest that for the IDs above, the pre-caching hasn't worked/been done.
Is there a way to check this? (or is my presumption wrong?)

**Comment by mgrbyte** [comment]
Closing as believe now fixed with AWS nginx config.
Can be re-opened if I'm wrong.
