### ISSUE TITLE
Configure a "stable" URL to front the ElasticBeanStalk instances

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase_rest#18]
Make it so we can use: `api.wormbase.org` (or similar) to point to the latest tagged version.

Investigate the best method of doing so (e.g API Gateway, Route53, ELB)

**Comment by adamjohnwright** [comment]
I have configured a CNAME "rest.prod.wormbase.org" that points at the EB WS257 URL. This will need to be changed when we do releases going forward. We will also need to make a "rest.dev.wormbase.org" when we role out WS258 to development. After that we might want to create make command that do this going forward. Will have to be coordinated with release of website.
