### ISSUE TITLE
WS_VERSION environment variable is not needed

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase_rest#58]
Re-implement the function in db.clj which currently uses `(env :ws-version)` to get it from the datomic-uri instead.

**Comment by adamjohnwright** [comment]
@mgrbyte Is your idea that th WS_VERSION that is currently provided through the env variable could be determined through the TRACE_DB URL?  If it is I could add in code to pull the WS version out of that variable - this way we would only need to set the one.

**Comment by mgrbyte** [comment]
@a8wright Yep, that's the idea. although my plan was to add an api (say `db-name`) to `pseudoace.core` or `pseudoace.utils` since we want the same logic across all projects.

I've actually started coding that, with some tests.
Additionally, I think it would be a good idea to rename the `TRACE_DB` environment variable to `WB_DB_URI` (or some such), since TRACE is specific to the trace/colonnade tool, and has no other meaning (the naming is a minor thing, but makes sense).

**Comment by mgrbyte** [comment]
Will fix with [imminent][1] pseudoace 0.4.15 release 

[1]:https://github.com/WormBase/pseudoace/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20milestone%3A0.4.15
