### ISSUE TITLE
overview widget: gene_cluster data is always nil/empty

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase_rest#62]
@sibyl229 @a8wright Wondering if this the same in the perl catalyst code or if this needs fleshing out to match?
See [here][1]

[1]: /WormBase/datomic-to-catalyst/blob/f51a8bf3619d39ee42be069a242a4e723644bcee/src/rest_api/classes/gene/widgets/overview.clj#L181

**Comment by sibyl229** [comment]
Hi @mgrbyte @a8wright It would need fleshing out. Here is the corresponding perl code: https://github.com/WormBase/website/blob/master/lib/WormBase/API/Object/Gene.pm#L414

**Comment by sibyl229** [comment]
Thanks @mgrbyte ! I will take a look

**Comment by sibyl229** [comment]
Note for myself, test case: /rest/field/gene/WBGene00001905/gene_cluster
