### ISSUE TITLE
URL format - need to convert dash to underscore

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#70]
The url for the widgets need the dash converted to underscore

ex: /rest/widget/gene/WBGene00015146/mapping-data

should be

/rest/widget/gene/WBGene00015146/mapping_data

**Comment by mgrbyte** [comment]
I believe I've already fixed this, and it's already in `develop`
I see, only for widget URLs (field URLs are ok)

**Comment by mgrbyte** [comment]
Verified that this is fixed in develop.
![endpoint-names-dtc-issue70](https://cloud.githubusercontent.com/assets/3185091/22657616/03ac4812-ec8f-11e6-98ed-8e47aa639b6d.png)
