### ISSUE TITLE
Handling of 404 responses

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/wormbase_rest#72]
This URL on staging does not produce a 404 response as I'd expect:

http://staging.wormbase.org/rest/widget/gene/WBGene00000421/overvie?content-type=application/json

(note the missing "w" in overview)

should we be trying to emulate this behaviour, or should any URL not matching a route return a 404 response (and if so, I assume in JSON? i.e `{:reason "These are not the worms you're looking for")`

I have a solution ready-to-go that implements the later. 
Matching the current (staging) behaviour would require more thought/work.

**Comment by sibyl229** [comment]
@mgrbyte The Catalyst code in this case is also problematic - doesn't through a 404 as needed. I like your suggested data structure. There is no need to mirror the catalyst behaviour here.
