### ISSUE TITLE
person/overview Also known as appearing when shouldn't be

### ISSUE THREAD

**Issue by adamjohnwright** [WormBase/wormbase_rest#92]
Here is an example: http://www.wormbase.org/resources/person/WBPerson30813#01--10

On the production website the also known as field does not show up where as when it is being pulled from d-t-c is is showing up with the value unknown. I think it would be better for it to not show up if there isn't any other name that we known the person as.

**Comment by azurebrd** [comment]
Fixed, making pull request.
